services:
  temp-app:
    image: sample-image
    container_name: Temp
    ports:
      - "9090:80"
    restart: unless-stopped

  virat-app:
    image: ubuntu
    container_name: virat_kohli
    command: tail -f /dev/null
    ports:
      - "9091:80"
    restart: unless-stopped

  web:
    image: nginx
    container_name: temp_cont
    ports:
      - "3000:80"
    restart: unless-stopped
