services:
  temp-app:
    image: sample-image
    container_name: temp
    ports:
      - "9090:80"
    restart: unless-stopped

  web:
    image: nginx
    container_name: temp_cont
    ports:
      - "3000:80"
    restart: unless-stopped

  front:
    image: eclipse-temurin:17
    container_name: java_container
    ports:
      - "9092:80"
    restart: unless-stopped
