version: '3'

services:

  temp-app:
    image: sample-image
    container_name: Temp
    ports:
      - "9090:80"
    restart: unless-stopped

  virat-app:
    image: rcb
    container_name: virat_kohli
    ports:
      - "9091:80"
    restart: unless-stopped

  web-app:
    image: nginx
    container_name: stupid
    ports:
      - "3000:80"
    restart: unless-stopped
